### ISSUE TITLE
Fantastic audit score!

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/week-5-dgjm#21]
<img width="1440" alt="Screenshot 2019-08-02 at 10 11 33" src="https://user-images.githubusercontent.com/36238916/62359116-15b71380-b50e-11e9-8134-6a4ddf3c11d3.png">
Great job guys!!
Maybe just change the colours a tiny bit to improve accessibility?
But otherwise fantastic!
<img width="436" alt="Screenshot 2019-08-02 at 10 12 20" src="https://user-images.githubusercontent.com/36238916/62359178-2c5d6a80-b50e-11e9-9a2f-0d1dd4863f0a.png">

**Comment by victormasson21** [comment]
Thanks, we'll try and improve the colour
