### ISSUE TITLE
Make the purpose of the countdown a bit clearer

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/week-5-dgjm#25]
<img width="886" alt="Screenshot 2019-08-02 at 10 16 08" src="https://user-images.githubusercontent.com/36238916/62359450-b73e6500-b50e-11e9-9a97-4e23dd6ed0d9.png">
I know what this is for because I've read the readme, but all the users that are going to be using your site will not know that this refers to Brexit - because you've not told them! Maybe you could make it a bit clearer what the countdown is for?

**Comment by mkatenolan** [comment]
I can second this one, think it's not entirely clear what's going on at the moment..you could make it a bit more obvious

**Comment by victormasson21** [comment]
We've changed the text, thank you!
