### ISSUE TITLE
Mobile 

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/week-5-dgjm#28]
<img width="1440" alt="Screenshot 2019-08-02 at 10 24 00" src="https://user-images.githubusercontent.com/36238916/62360009-cffb4a80-b50f-11e9-84ba-cd42f18307a0.png">
It looks pretty decent on mobile - but perhaps add more space in between the elements so that there's not a big chunk of the screen not being utilised.

**Comment by mkatenolan** [comment]
In addition, the dropdown list could use some adjustment on mobile
