### ISSUE TITLE
Cursor: pointer

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/week-5-dgjm#29]
Pet peeve of mine but I always look for a cursor: pointer over a button. Add one! Great for the user to know he/she is supposed to interact with that element, and it's such a design axiom that many people will think the button won't work if there's no pointer.

https://uxdesign.cc/missing-the-pointer-1dfc5cd60c8c

P.S. Grammar in this article is TERRIBLE (sorry Mr Journalist) but the content is fairly useful.

**Comment by victormasson21** [comment]
If i had a penny for every time Georgia made me add a pointer cusor... i'd have about 3 pennies right now 💸
