### ISSUE TITLE
Readme!

### ISSUE THREAD

**Issue by Oliversw** [fac-17/week-5-dgjm#34]
Nice work on the readme, it looks great! I love the process and also the section for code snippets for later 😉 

Don't forget about installation instructions! Especially now that things are getting more complicated and we're introducing .env files among other things, it's worth being really explicit about how to install and run the project locally, even if it does end up being very simple.

**Comment by victormasson21** [comment]
We'll work to improve the installation instructions, thanks for the feedback!
