### ISSUE TITLE
LOVE the concept

### ISSUE THREAD

**Issue by georgiamshaw** [fac-17/week-5-dgjm#35]
REALLY like the idea... No one knows or cares about the price of things like the Japanese yen or the Canadian dollar, despite the fact that it affects everyone.

It'd be SUPER cool to have a comparison with more previous months or years to have a better idea of what the numbers mean. Stretch goal flex here! 💪

**Comment by victormasson21** [comment]
No one cares about the Japanese?

I think 25% of this cohort would disagree Georgia 😱
