### ISSUE TITLE
Date of currency rate

### ISSUE THREAD

**Issue by Oliversw** [fac-17/week-5-dgjm#37]
I'm not sure if this is known (or somehow intended), since I have only had a chance to briefly look at the project, but from the readme I understand that the currency updates are meant to be live. 
When I was looking at the application however, it was very explicitly telling me about exchange rates from 2015 so just wanted to point that out! Ignore me if this is somehow part of what you intended 🙂

**Comment by gminova** [comment]
Our daily currency was not working. it should be working now. the old data is just hardcoded for comparison to realise how much poorer we are becoming :D
