### ISSUE TITLE
backend api requests not returning a response due to redirection (not your fault at all!)

### ISSUE THREAD

**Issue by reubengt** [fac-17/week-5-dgjm#41]
Took a while to find the cause of this error, but basically all your get requests to the api were failing.

console logged the actual response from your api.js file, and found that it had a statuscode 301.

then noticed that the url you're making the request to(https://api.ratesapi.io/api/latest?base=GBP), when typed in the address bad, redirects to a different url. 'https://api.exchangeratesapi.io/api/latest?base=GBP'

change your handleQuery function to have the updated url to pass on to the myRequest function.

```javascript=
function handleQuery(req, res, endpoint) {
  //let input = endpoint.split('=')[1];
  let url = "https://api.exchangeratesapi.io/api/latest?base=GBP";

  myRequest(url, (err, result) => {
    if(err) {
        res.end("Error");
    } else {
      console.log(result);
      res.end(JSON.stringify(result.body.rates));
    }
  });
}
```

**Comment by gminova** [comment]
fixed! Thanks mate!! fixes #44
